### ISSUE TITLE
Add docs, testing, checking as optional dependencies

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digital-archive#36]
Installing everything all the time is heavy. We can group them into optionals instead. For example

```toml
[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8"
mypy = "^0.730.0"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
flake8 = "^3.7"
sphinx = {version = "^2.2", optional = true}
sphinx_rtd_theme = {version = "^0.4.3", optional = true}


[tool.poetry.extras]
docs = ["sphinx", "sphinx_rtd_theme"]
```
would make `sphinx` and `sphinx_rtd_theme` optional dependencies that could be installed with `poetry install -E docs`
