### ISSUE TITLE
Add build/deploy to CI/CD

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digital-archive#60]
It would be nice to add a build/deploy step to our CI/CD so digiarch can live on PyPI. Structure suggestion:
```yaml
workflows:
  version: 2.1
  development:
    jobs:
      - check
      - test
  release:
    jobs:
      - test
      - build
      - deploy
```
We'd need to separate the check and test jobs, as well as create build and deploy jobs for CircleCI.
