### ISSUE TITLE
Speed up CI/CD with caching

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digital-archive#61]
Cf https://dev.to/jonatasbaldin/a-recipe-for-poetry-and-circleci-1bj6 we could probably update the init command like so:

```yaml
commands:
  # Initialises the docker image and updates dependencies using poetry
  init:
    steps:
      # Get current code base
      - checkout
      # Restore cache (if exists)
      - restore_cache:
          keys: 
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Python dependencies
          # Install dependencies using poetry.
          command: poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs
```
This would enable MUCH faster job times, as our current overhead is the `poetry install` call
