### ISSUE TITLE
Update pyproject with extra metadata for PyPI

### ISSUE THREAD

**Issue by jnik-aarhus** [aarhusstadsarkiv/digital-archive#73]
Add readme.md, repository/homepage/docs info to `pyproject.toml` - like this:
```toml
readme = "README.md"
homepage = "link"
repository = "link"
documentation = "link"
keywords = ["x", "y", "z"]
```
